# Generated by Django 6.1 on 2026-08-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
                ('token_encrypted', models.BinaryField()),
                ('ca_cert', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('state', models.CharField(choices=[('CREATING', 'Creating'), ('ACTIVE', 'Active'), ('DELETING', 'Deleting'), ('CREATE_FAILED', 'Create Failed'), ('DELETE_FAILED', 'Delete Failed'), ('MISSING', 'Missing'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='core.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('image', models.CharField(max_length=255)),
                ('replicas', models.PositiveIntegerField(default=1)),
                ('cpu', models.CharField(default='100m', max_length=32)),
                ('memory', models.CharField(default='128Mi', max_length=32)),
                ('state', models.CharField(choices=[('CREATING', 'Creating'), ('ACTIVE', 'Active'), ('UPDATING', 'Updating'), ('DELETING', 'Deleting'), ('CREATE_FAILED', 'Create Failed'), ('UPDATE_FAILED', 'Update Failed'), ('DELETE_FAILED', 'Delete Failed'), ('MISSING', 'Missing'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='core.namespace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='unique_namespace_per_cluster'),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='unique_app_per_namespace'),
        ),
    ]
