# Generated by Django 6.1 on 2026-08-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('backup_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('source_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.app')),
            ],
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=512)),
                ('cron_minute', models.CharField(default='*', max_length=10)),
                ('cron_hour', models.CharField(default='*', max_length=10)),
                ('cron_day_of_month', models.CharField(default='*', max_length=10)),
                ('cron_month_of_year', models.CharField(default='*', max_length=10)),
                ('cron_day_of_week', models.CharField(default='*', max_length=10)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='core.app')),
            ],
        ),
    ]
